[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[all]>=0.115.13",
    "funasr>=1.2.6",
    "httpx>=0.28.1",
    "invoke>=2.2.0",
    "pyinstaller>=6.14.1",
    "torch>=2.7.1",
    "torchaudio>=2.7.1",
]
